### ISSUE TITLE
Bats will do handstands on the ground.

### ISSUE THREAD

**Issue by baotangJC** [VenomiXeD/SmallBatsMod#1]

**Comment by VenomiXeD** [comment]
The intended idea is for bats to "stand" on the ground. However it appears that it is more or less not really that good looking. It'll be removed.

**Comment by VenomiXeD** [comment]
Fixed in https://github.com/VenomiXeD/SmallBatsMod/commit/f81a0175fa068bdbcc1525c2abcd2f36a73aab33
